### ISSUE TITLE
Django 1.9 support

### ISSUE THREAD

**Issue by mikaelengstrom** [jbittel/django-mama-cas#25]
Hi, just upgraded to django 1.9 and got this:

```

$ ./src/manage.py test
Traceback (most recent call last):
  File "./src/manage.py", line 20, in <module>
    execute_from_command_line(sys.argv)
  File "/xxx/venv/lib/python2.7/site-packages/django/core/management/__init__.py", line 350, in execute_from_command_line
    utility.execute()
  File "/xxx/venv/lib/python2.7/site-packages/django/core/management/__init__.py", line 324, in execute
    django.setup()
  File "/xxx/venv/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/xxx/venv/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/xxx/venv/lib/python2.7/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/xxx/venv/lib/python2.7/site-packages/mama_cas/models.py", line 14, in <module>
    from django.utils.http import same_origin
ImportError: cannot import name same_origin
```

**Comment by jbittel** [comment]
This specific issue has been fixed in the latest development code, per #22. Now that 1.9 is officially out, I'm planning to do a full release with 1.9  support and drop support for unsupported Django versions.

Thanks!
